title: Mritunjay Sharma
subtitle: An automating polyglot, jack of all trades, master of some.
description: >- # this means to ignore newlines until "baseurl:"
  testing content. will add later.

url: "https://mritunjaysharma394.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
 #   - text: Projects
#      url: /projects
#    - text: Shop
#     url : /shop
    - text: Contact Me
      url : /contact
#   - text: Styleguide
#      url: /styleguide
#   - text: Get Started
#     url: /get-started

# Edit these details

author_logo: profile.jpg
author: Mritunjay Sharma
author_bio: Hi, my name is Mritunjay Sharma, a Computer Science Engineering Student, exlporing the tryst with Open-Source, delving into Python, framing things with Django, while dealing in Flasks, with a pinch of Shell scripts, a hint of C/C++ development in the kernel that is not found in the corn to finally try and automate all of it and sometimes writing poems, just like this one?
author_email: "mritunjaysharma394@gmail.com"
author_location: India
typewrite-text: a Computer Science Engineering Student, exlporing the tryst with Open-Source, delving into Python, framing things with Django, while dealing in Flasks, with a pinch of Shell scripts, a hint of C/C++ development in the kernel that is not found in the corn to finally try and automate all of it and sometimes writing poems, just like this one?

author_work_experiences:
            - company_name: Google Summer of Code
              company_logo: gsoc.png
              company_url: https://bit.ly/gsoc-2020-final-report
              designation: Student Developer at RTEMS
              description: Built a CI System - a program that autonomously forms a functional interface between larger software solutions such as RTEMS and EPICS, without the need for on-site IT specialists to assist in the adaptation process
              visibility: true
            - company_name: Uttar Pradesh Metro Railway Corporation
              company_logo: upmrc.png
              company_url: https://www.lmrcl.com/
              designation: Summer Intern
              description: Worked on developing a CRUD Notice Board Web Application using Django Framework. The result of this project was that it increased the coherency of six departments under the Corporation
              visibility: true

author_education_details:
              - college_logo: jss.png
                college_name: JSS Academy of Technical Education, Noida (Affiliated to Dr. APJ Abdul Kalam Technical University)
                college_url: https://jssaten.ac.in/
                college_degree: Computer Science Engineering
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: SedPy.png
                project_title: sedpy
                project_description: sedpy is an open-source project being built as a cross-platform alternative of sed for easier and more flexible stream line editing across BSD and GNU systems.
                project_url: https://pypi.org/project/sedpy/1.0.0/
                visibility: true
              - project_thumbnail: github-azure.png
                project_title: Automating Image Classification with Microsoft Azure Custom Vision Training and Prediction
                project_description: A low-code/no-code Image Classifier GitHub Action which uses Microsoft Azure Custom Vision Services. It gives user the ability to train and publish Image Classification Model without writing a single line of python code by just pushing the image data-set and workflow file in the GitHub repository.
                project_url: https://github.com/marketplace/actions/automating-image-classification-with-microsoft-azure-custom-vision-training-and-prediction
                visibility: true
              - project_thumbnail: github-python.jpeg
                project_title: autoyapf
                project_description: autoyapf is a GitHub action for yapf, an open-source tool that automatically formats Python code to conform to the PEP 8 style guide.
                project_url: https://github.com/marketplace/actions/autoyapf
                visibility: true
# social links
twitter_username: mritunjay394
github_username:  mritunjaysharma394
facebook_username: mritunjaykumar.sharma.18
linkedin_username: mritunjay394
medium_username: mritunjay394


#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: mritunjaysharma394@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jemoji
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
